query GetRandomTriviaByParams($exam: ExamList!, $subject: SubjectList!) {
  getRandomTriviaByParams(exam: $exam, subject: $subject) {
    ...TriviaSnippet
    answers {
      ...TriviaAnswerSnippet
    }
  }
}
