query GetRandomTriviaByParams(
  $exam: ExamList
  $subjectID: Int!
  $triviaType: TriviaType!
) {
  getRandomTriviaByParams(
    exam: $exam
    subject_id: $subjectID
    type: $triviaType
  ) {
    ...TriviaSnippet
    answers {
      ...TriviaAnswerSnippet
    }
    subject {
      ...SubjectSnnipet
    }
  }
}
